name: USPSA Match Auto-Registration

on:
  schedule:
    # Run every day at 10:00 PM Central Time (3:00 AM UTC)
    - cron: '0 3 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  check-matches:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
    
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
    
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run match checker
      env:
        PRACTISCORE_USERNAME: ${{ secrets.PRACTISCORE_USERNAME }}
        PRACTISCORE_PASSWORD: ${{ secrets.PRACTISCORE_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
        # Registration details for automatic form filling
        REGISTRATION_FIRST_NAME: ${{ secrets.REGISTRATION_FIRST_NAME }}
        REGISTRATION_LAST_NAME: ${{ secrets.REGISTRATION_LAST_NAME }}
        REGISTRATION_EMAIL: ${{ secrets.REGISTRATION_EMAIL }}
        REGISTRATION_POWER_FACTOR: ${{ secrets.REGISTRATION_POWER_FACTOR }}
        # Optional Twilio credentials (if you set up paid SMS)
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
        # Display for Chrome
        DISPLAY: :99
      run: |
        echo "=== Running Chrome Debug Test ==="
        xvfb-run --auto-servernum --server-num=1 python debug_chrome.py
        echo "=== Running Match Registrar ==="
        xvfb-run --auto-servernum --server-num=1 python match_registrar.py
    
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: match-registrar-logs
        path: match_registrar.log